# -*- coding: utf-8 -*-
"""Lab 8 CV

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c75h2a2Qyx5sIAsx5Ksc3niZckVT1y3p
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install diffusers transformers accelerate safetensors insightface onnxruntime opencv-python-headless -q
!pip install ip-adapter facexlib gfpgan -q

import os

PROJECT_ROOT = "/content/Lab6_CV"
os.makedirs(PROJECT_ROOT, exist_ok=True)

MODEL_DIR = os.path.join(PROJECT_ROOT, "models")
IMAGES_DIR = os.path.join(PROJECT_ROOT, "generated_images")
SOURCE_DIR = os.path.join(PROJECT_ROOT, "source_photos")

for dir_path in [MODEL_DIR, IMAGES_DIR, SOURCE_DIR]:
    os.makedirs(dir_path, exist_ok=True)

print(f"Thư mục dự án: {PROJECT_ROOT}")
print(f"Tải ảnh lên: {SOURCE_DIR}")

#  Tải model IP-Adapter

import torch
from diffusers import StableDiffusionPipeline, DDIMScheduler

SD_MODEL = "runwayml/stable-diffusion-v1-5"
ADAPTER_PATH = os.path.join(MODEL_DIR, "ip_adapter_faceid.bin")

# Tải adapter nếu chưa có
if not os.path.exists(ADAPTER_PATH):
    !wget -q "https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid_sd15.bin" \
        -O {ADAPTER_PATH}
    print("Downloaded IP-Adapter FaceID")

scheduler = DDIMScheduler.from_pretrained(SD_MODEL, subfolder="scheduler")
pipe = StableDiffusionPipeline.from_pretrained(
    SD_MODEL,
    scheduler=scheduler,
    torch_dtype=torch.float16,
    safety_checker=None,
    requires_safety_checker=False
)
pipe = pipe.to("cuda")

pipe.enable_attention_slicing()

print("Model loaded successfully")

#  Khởi tạo Face Analyzer và IP-Adapter

from insightface.app import FaceAnalysis
from ip_adapter.ip_adapter_faceid import IPAdapterFaceID
import cv2
import numpy as np

# Face analysis
face_analyzer = FaceAnalysis(
    name="buffalo_l",
    providers=['CUDAExecutionProvider', 'CPUExecutionProvider']
)
face_analyzer.prepare(ctx_id=0, det_size=(640, 640))
print("Face analyzer sẵn sàng")

# IP-Adapter
face_adapter = IPAdapterFaceID(
    pipe,
    ADAPTER_PATH,
    device="cuda"
)
print("IP-Adapter FaceID sẵn sàng")

# Upload ảnh khuôn mặt

from google.colab import files
import os
import shutil

SOURCE_DIR = "/content/Lab6_CV/source_photos"
os.makedirs(SOURCE_DIR, exist_ok=True)

print("UPLOAD ẢNH KHUÔN MẶT CỦA BẠN")

uploaded = files.upload()

for filename, content in uploaded.items():
    filepath = os.path.join(SOURCE_DIR, filename)
    with open(filepath, 'wb') as f:
        f.write(content)
    print(f"Đã lưu: {filename}")

print("DANH SÁCH ẢNH ĐÃ UPLOAD:")

import glob
image_paths = glob.glob(os.path.join(SOURCE_DIR, "*.[jJ][pP][gG]")) + \
               glob.glob(os.path.join(SOURCE_DIR, "*.[pP][nN][gG]"))

for i, path in enumerate(image_paths, 1):
    print(f"{i}. {os.path.basename(path)}")

print(f"\nTổng số: {len(image_paths)} ảnh")

# Hiển thị ảnh đầu tiên
if len(image_paths) > 0:
    from PIL import Image
    import matplotlib.pyplot as plt

    sample = Image.open(image_paths[0])
    plt.figure(figsize=(5,5))
    plt.imshow(sample)
    plt.title("Ảnh tham chiếu của bạn", fontsize=12)
    plt.axis("off")
    plt.show()

#  Trích xuất đặc trưng khuôn mặt

def extract_face_features(image_paths, face_analyzer):
    """Trích xuất face embedding từ nhiều ảnh"""
    embeddings = []
    valid_images = []

    for img_path in image_paths:
        img = cv2.imread(img_path)
        if img is None:
            continue

        # Resize về kích thước chuẩn
        img = cv2.resize(img, (640, 640))

        # Phát hiện khuôn mặt
        faces = face_analyzer.get(img)

        if len(faces) > 0:
            face = faces[0]
            if face.det_score > 0.5:  # Chỉ lấy mặt có chất lượng tốt
                embeddings.append(face.normed_embedding)
                valid_images.append(img_path)
                print(f"Đã nhận diện: {os.path.basename(img_path)} (score: {face.det_score:.2f})")
            else:
                print(f"Chất lượng thấp: {os.path.basename(img_path)}")
        else:
            print(f"Không tìm thấy mặt: {os.path.basename(img_path)}")

    if len(embeddings) == 0:
        raise ValueError("Không có ảnh nào hợp lệ!")

    # Lấy embedding trung bình để tăng độ chính xác
    avg_embedding = np.mean(embeddings, axis=0)
    face_tensor = torch.from_numpy(avg_embedding).unsqueeze(0).float()

    print(f"\nTổng hợp từ {len(embeddings)} ảnh")
    return face_tensor.to("cuda")

# Trích xuất
face_embedding = extract_face_features(image_paths, face_analyzer)

# Hàm sinh ảnh với face preservation

def generate_with_my_face(
    prompt,
    face_embedding,
    adapter,
    num_steps=50,
    guidance_scale=7.5,
    face_strength=0.85,
    seed=None
):
    """
    Sinh ảnh giữ được khuôn mặt
    - prompt: text mô tả
    - face_strength: độ mạnh của face preservation (0.5-1.0)
    """
    # Tạo generator cho seed
    generator = torch.Generator(device="cuda").manual_seed(seed) if seed is not None else None

    # Gọi adapter.generate - KHÔNG truyền generator qua kwargs
    images = adapter.generate(
        prompt=prompt,
        faceid_embeds=face_embedding,
        num_samples=1,
        num_inference_steps=num_steps,
        guidance_scale=guidance_scale,
        scale=face_strength,
        seed=seed
    )
    return images[0]

# Test thử
print(" Đang test sinh ảnh...")
test_img = generate_with_my_face(
    "portrait photo, high quality, detailed face",
    face_embedding,
    face_adapter,
    num_steps=30,
    seed=42
)

plt.figure(figsize=(5,5))
plt.imshow(test_img)
plt.title("Test sinh ảnh với khuôn mặt của bạn", fontsize=12)
plt.axis("off")
plt.show()
print("Test thành công.")

#  Tạo 1 ảnh chất lượng cao nhất
# Prompt được tối ưu cho chất lượng cao
best_prompt = """
a girl, professional photograph, cinematic lighting,
detailed face, sharp focus, 8K resolution,
masterpiece, award winning photo
""".strip()

# Thử nhiều seed để chọn ảnh đẹp nhất
candidates = []
seeds_to_try = [42, 123, 456, 789, 101112]

for seed in seeds_to_try:
    print(f"Đang thử seed {seed}...")
    img = generate_with_my_face(
        prompt=best_prompt,
        face_embedding=face_embedding,
        adapter=face_adapter,
        num_steps=60,
        guidance_scale=8.0,
        face_strength=0.9,
        seed=seed
    )
    candidates.append((seed, img))

# Hiển thị để chọn
fig, axes = plt.subplots(1, 5, figsize=(20, 5))
for i, (seed, img) in enumerate(candidates):
    axes[i].imshow(img)
    axes[i].set_title(f"Seed: {seed}", fontsize=10)
    axes[i].axis("off")
plt.suptitle("Chọn ảnh đẹp nhất (click vào cửa sổ console để chọn)", fontsize=14)
plt.tight_layout()
plt.show()

# Chọn ảnh đẹp nhất
choice = input("\nNhập seed của ảnh đẹp nhất (42/123/456/789/101112): ")
best_seed = int(choice)
best_image = next(img for s, img in candidates if s == best_seed)

# Lưu
best_image.save(os.path.join(IMAGES_DIR, "best_quality_image.png"))
print(f"Đã lưu ảnh chất lượng cao tại: {IMAGES_DIR}/best_quality_image.png")

# Tạo 5 ảnh theo phong cách khác nhau
style_configs = [
    {
        "name": "Victorian Era",
        "prompt": "a girl in victorian era dress, old library, vintage, high quality, realism"
    },
    {
        "name": "Ice Queen",
        "prompt": "a girl made of ice, frozen crystal, winter fantasy, snowflake details, high quality"
    },
    {
        "name": "Flower Fairy",
        "prompt": "a girl as flower fairy, petals floating, magical garden, soft lighting, high quality"
    },
    {
        "name": "Art Deco",
        "prompt": "a girl in art deco style, 1920s glamour, geometric patterns, gold details, high quality"
    },
    {
        "name": "Underwater",
        "prompt": "a girl underwater, bubbles, coral reef, ocean light rays, high quality, realism"
    }
]

style_images = []

for i, config in enumerate(style_configs, 1):
    print(f"\n [{i}/5] Đang tạo: {config['name']}")

    img = generate_with_my_face(
        prompt=config['prompt'],
        face_embedding=face_embedding,
        adapter=face_adapter,
        num_steps=50,
        guidance_scale=7.5,
        face_strength=0.85,
        seed=200 + i
    )
    style_images.append((config['name'], img))
    img.save(os.path.join(IMAGES_DIR, f"style_{i:02d}_{config['name']}.png"))

# Hiển thị grid 5 ảnh
fig, axes = plt.subplots(1, 5, figsize=(20, 5))
for i, (name, img) in enumerate(style_images):
    axes[i].imshow(img)
    axes[i].set_title(name, fontsize=12, fontweight='bold')
    axes[i].axis("off")
plt.suptitle("5 PHONG CÁCH KHÁC NHAU", fontsize=16, fontweight='bold')
plt.tight_layout()
plt.savefig(os.path.join(IMAGES_DIR, "five_styles_collage.png"), dpi=150)
plt.show()

print(f"\n Đã lưu 5 ảnh phong cách vào: {IMAGES_DIR}")

# Tạo 3 ảnh theo địa điểm (Yêu cầu chính) \
location_images = []

# Prompt template theo yêu cầu đề bài
locations = [
    ("Forest", "a mystical forest with tall pine trees, morning fog, sun rays through leaves, moss on ground, peaceful atmosphere"),
    ("City", "a bustling modern city street at golden hour, glass skyscrapers, city lights starting to glow, reflections on wet pavement"),
    ("Beach", "a pristine white sand beach with turquoise water, gentle waves, palm trees, golden sunset sky, tropical paradise")
]

for i, (name, location_detail) in enumerate(locations, 1):
    prompt = f"a girl in {location_detail}, high quality, realism"
    print(f"\n [{i}/3] Đang tạo: {name}")

    img = generate_with_my_face(
        prompt=prompt,
        face_embedding=face_embedding,
        adapter=face_adapter,
        num_steps=55,
        guidance_scale=7.5,
        face_strength=0.85,
        seed=300 + i
    )
    location_images.append((name, img))
    img.save(os.path.join(IMAGES_DIR, f"location_{i:02d}_{name}.png"))
    print(f"   Đã lưu: location_{i:02d}_{name}.png")

# Hiển thị kết quả
fig, axes = plt.subplots(1, 3, figsize=(15, 5))
for i, (name, img) in enumerate(location_images):
    axes[i].imshow(img)
    axes[i].set_title(f" {name}", fontsize=12, fontweight='bold')
    axes[i].axis("off")
plt.suptitle('"a girl in a forest - city - beach"', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(os.path.join(IMAGES_DIR, "three_locations.png"), dpi=150)
plt.show()

print(f"\n Đã lưu 3 ảnh theo địa điểm vào: {IMAGES_DIR}")